// Generated by scripts/client-ts.sh from the compiled route table.
//
// Do not edit. The table this was projected from is the table the dispatcher
// runs — `tests/boot/check.sh` regenerates this file and refuses a difference,
// so an edit here is reverted by the build rather than by a reviewer.
//
// A wrong path or a wrong method is a compile error at the call site:
//
//     await client.get("/sum");     // Error: "/sum" is not a GET route
//     await client.post("/hello");  // Error: "/hello" is not a POST route
//
// The status codes are the closed RouteResult the dispatcher returns, so a
// caller handling every member has handled every outcome the server has.

export type BootStatus = 200 | 404 | 405 | 413;

export interface BootResponse<T = unknown> {
  status: BootStatus;
  body: T;
  /** Present on 405 — the methods the dispatcher would have accepted. */
  allow?: readonly BootMethod[];
}

export type BootMethod = "get" | "post";

export type GetPath =
  | "/hello"
  | "/bench"
  | `/things/${number}`

export type PostPath =
  | "/sum"
  | "/bench"

export interface BootClientOptions {
  /** Base URL, e.g. "http://127.0.0.1:8080". No default: a client that
   *  silently picks a host is a client that talks to the wrong one. */
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
}

export function createClient(options: BootClientOptions) {
  const doFetch = options.fetch ?? globalThis.fetch;
  const base = options.baseUrl.replace(/\/+$/, "");

  async function send<T>(
    method: BootMethod,
    path: string,
    body?: unknown,
  ): Promise<BootResponse<T>> {
    const response = await doFetch(`${base}${path}`, {
      method: method.toUpperCase(),
      headers: body === undefined ? {} : { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const allow = response.headers.get("allow");
    return {
      status: response.status as BootStatus,
      body: (await response.json().catch(() => undefined)) as T,
      ...(allow
        ? { allow: allow.toLowerCase().split(/,\s*/) as BootMethod[] }
        : {}),
    };
  }

  return {
    get: <T = unknown>(path: GetPath) => send<T>("get", path),
    post: <T = unknown>(path: PostPath, body?: unknown) =>
      send<T>("post", path, body),
  };
}
