-- Generated by scripts/ddl.sh from the migration history the schema binary printed.
-- Do not edit: tests/schema/check.sh regenerates this file and fails on
-- any difference.
-- dialect: postgresql
-- contract: 1

-- step 1: create table (primary key 1)
create table users (
    id bigint not null, -- key 1
    primary key (id)
);

-- step 2: add column (key 2)
alter table users add column email text;

-- step 3: add column (key 3)
alter table users add column name text;

-- step 4: add column (key 4)
alter table users add column nickname text;

-- step 5: rename column (key 3)
alter table users rename column name to display_name;

-- step 6: set not null (key 2), policy backfilled
-- precondition: every existing row already holds a value
alter table users alter column email set not null;

-- step 7: drop column (key 4), policy discard: its data is destroyed
alter table users drop column nickname;
