-- Generated by scripts/ddl.sh from the declared schema the schema binary printed.
-- Do not edit: tests/schema/check.sh regenerates this file and fails on
-- any difference.
-- dialect: postgresql
-- contract: 1

create table users (
    id bigint not null, -- key 1
    email text not null, -- key 2
    display_name text, -- key 3
    primary key (id)
);
-- users: retired keys, never to be reissued: 4

create table posts (
    id bigint not null, -- key 1
    author_id bigint not null references users (id), -- key 2
    views bigint, -- key 3
    primary key (id)
);

-- marker: the schema digest this database now holds
create table if not exists kofun_schema_marker (
    digest bigint not null
);
delete from kofun_schema_marker;
insert into kofun_schema_marker (digest) values (177800485);
