-- Generated by scripts/ddl.sh from the declared schema the schema binary printed.
-- Do not edit: tests/schema/check.sh regenerates this file and fails on
-- any difference.
-- dialect: postgresql
-- contract: 1

create table users (
    id bigint not null, -- key 1
    email text not null, -- key 2
    display_name text, -- key 3
    primary key (id)
);

-- retired keys, never to be reissued: 4
