-- Generated by scripts/shape-sql.sh from the shapes the loader binary printed.
-- Do not edit: tests/loader/check.sh regenerates this file and fails on
-- any difference.
-- dialect: postgresql
-- contract: 1

-- shape: authors with their post ids, load join: 1 statement
select a.id, coalesce(children.post_ids, '[]'::json) as post_ids
from authors a
left join lateral (
    select json_agg(p.id order by p.id) as post_ids
    from posts p
    where p.author_id = a.id
) as children on true
order by a.id;

-- shape: authors with their post ids, load split: 2 statements
select a.id
from authors a
order by a.id;
select p.author_id, json_agg(p.id order by p.id) as post_ids
from posts p
where p.author_id = any($1)
group by p.author_id
order by p.author_id;
