#!/bin/sh
set -eu

# Compile the application's boot.conf into the value the shell resolves.
#
#   scripts/boot-config.sh [BOOT_CONF]
#
# Prints Kofun source defining boot_input(); modules/config/shell/input.kofun
# is that output for modules/config/boot.conf, and tests/config/check.sh
# refuses a copy that is not.
#
# boot.conf is text, one setting per line, `#` to the end of a line ignored:
#
#   packs = http_minimal, http_strict
#   http.port = 9090
#
# This is the only place configuration text is read. It happens at build
# time, so the binary reads no file and no environment, and the record it
# resolves is the same under `env -i`. Here, and only here, a name is checked
# against the names that exist: an unknown key or pack is refused with the
# nearest real one, the way a typo deserves. Whether a value is in range, and
# whether two packs conflict, is the core's check, made on codes.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
. "$ROOT/scripts/boot-names.sh"

conf=${1:-"$ROOT/modules/config/boot.conf"}
test -f "$conf" || { printf 'boot-config: no such file: %s\n' "$conf" >&2; exit 2; }
label=$(basename -- "$conf")

fail() {
    printf 'boot-config: %s\n' "$*" >&2
    exit 1
}

packs=''
packs_line=0
slots=0
k1=0; v1=0; l1=0
k2=0; v2=0; l2=0
k3=0; v3=0; l3=0
number=0
while IFS= read -r raw || test -n "$raw"; do
    number=$((number + 1))
    line=$(printf '%s' "$raw" | sed 's/#.*$//; s/^[[:space:]]*//; s/[[:space:]]*$//')
    test -n "$line" || continue
    case $line in
        *=*) ;;
        *) fail "$label:$number: expected 'key = value', got: $line" ;;
    esac
    key=$(printf '%s' "${line%%=*}" | sed 's/[[:space:]]*$//')
    value=$(printf '%s' "${line#*=}" | sed 's/^[[:space:]]*//')
    if test "$key" = packs; then
        test "$packs_line" = 0 || fail "$label:$number: packs is already set on line $packs_line"
        packs_line=$number
        packs=0
        for name in $(printf '%s' "$value" | tr ',' ' '); do
            bit=$(boot_pack_bit "$name") ||
                fail "$label:$number: unknown pack $name; did you mean $(boot_nearest "$name" $BOOT_PACK_NAMES)?"
            test $((packs / bit % 2)) = 0 || fail "$label:$number: pack $name is listed twice"
            packs=$((packs + bit))
        done
        continue
    fi
    code=$(boot_field_code "$key") ||
        fail "$label:$number: unknown key $key; did you mean $(boot_nearest "$key" $BOOT_FIELD_NAMES)?"
    written=$(boot_value_code "$code" "$value") ||
        fail "$label:$number: $key takes $(boot_value_hint "$code"), not '$value'"
    slots=$((slots + 1))
    case $slots in
        1) k1=$(boot_field_fn "$code"); v1=$written; l1=$number ;;
        2) k2=$(boot_field_fn "$code"); v2=$written; l2=$number ;;
        3) k3=$(boot_field_fn "$code"); v3=$written; l3=$number ;;
        *) fail "$label:$number: the seed holds three overrides; this is the fourth" ;;
    esac
done <"$conf"

if test "$packs_line" = 0; then
    packs=1
fi
pack_source=''
for bit in 1 2 4 8; do
    if test $((packs / bit % 2)) = 1; then
        pack_source=${pack_source:+"$pack_source + "}$(boot_pack_fn "$bit")
    fi
done
# No packs at all is a choice the core refuses, by name; say it in source.
pack_source=${pack_source:-0}

printf '# Generated by scripts/boot-config.sh from %s. Do not edit:\n' \
    "${conf#"$ROOT"/}"
printf '# change boot.conf and regenerate this file.\n'
printf 'fn boot_input() -> BootInput {\n'
printf '    return boot_input_of(\n'
printf '        %s,\n' "$pack_source"
printf '        %s, %s, %s,\n' "$k1" "$v1" "$l1"
printf '        %s, %s, %s,\n' "$k2" "$v2" "$l2"
printf '        %s, %s, %s\n' "$k3" "$v3" "$l3"
printf '    )\n'
printf '}\n'
