#!/bin/sh
set -eu

# Project the compiled route table into a TypeScript client.
#
# Same input as the OpenAPI projection and for the same reason: the twelve
# lines the router itself printed, which the gate pins as the compiled table.
# A client generated from those bytes cannot call a route the dispatcher does
# not serve.
#
# What swagger-codegen cannot offer, and this can: the document it consumes
# was written *beside* the server, so a generated client is only as true as
# whoever kept the document current. Here there is no document in the middle —
# the client and the dispatcher read the same bytes, and drift is a build
# failure rather than a stale artifact.
#
# The emitted client is typed so that a wrong path or a wrong method is a
# compile error at the call site, not a 404 at runtime. `client.get("/sum")`
# does not type-check, because `/sum` is POST-only in the table.
#
# usage: scripts/client-ts.sh [BUILT_ROUTER]

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

fail() {
    printf 'client-ts: %s\n' "$*" >&2
    exit 1
}

router=${1:-}
if test -z "$router"; then
    router=$(sh "$ROOT/scripts/build-seed.sh" "$ROOT/build/router")
fi
test -x "$router" || fail "no built router at $router"

table=$("$router" | sed -n '1,20p')
test "$(printf '%s\n' "$table" | wc -l)" -eq 20 ||
    fail 'the router did not print a twenty-line table'

# The seam the slice forces, shared with the OpenAPI projection: the table
# carries path codes because a record cannot hold Text. Resolved up front, in
# this shell — a `fail` inside a command substitution exits only the subshell,
# which is how an unnamed route once produced an empty name and a clean exit.
path_name() {
    case $1 in
        101) printf '/hello' ;;
        102) printf '/sum' ;;
        103) printf '/bench' ;;
        104) printf '/things/{id}' ;;
        *) return 1 ;;
    esac
}

# What a route contributes to a path union. A literal route is a string
# literal, so only that exact path type-checks. A capturing route is a
# template literal type: `/things/${number}` accepts /things/7 and rejects
# /things/seven, and — the point — does not accept the template itself.
# Emitting "/things/{id}" as a literal would make the one call nobody can
# perform the only one that compiles.
path_type() {
    if test "$2" = 1; then
        printf '`%s`' "$(path_name "$1" | sed 's/{id}/${number}/')"
    else
        printf '"%s"' "$(path_name "$1")"
    fi
}

method_name() {
    case $1 in
        1) printf 'get' ;;
        2) printf 'post' ;;
        *) return 1 ;;
    esac
}

rows=$(printf '%s\n' "$table" | paste - - - -)
codes=$(printf '%s\n' "$rows" | awk '{print $2}' | sort -un)

for code in $codes; do
    path_name "$code" >/dev/null ||
        fail "route code $code has no path name; add it to scripts/client-ts.sh"
done
for method in $(printf '%s\n' "$rows" | awk '{print $1}' | sort -un); do
    method_name "$method" >/dev/null ||
        fail "method code $method is not in the contract"
done

emit_route_union() {
    wanted=$1
    first=1
    printf '%s\n' "$rows" | while IFS='	' read -r method path handler capture; do
        test "$(method_name "$method")" = "$wanted" || continue
        if test "$first" -eq 1; then
            printf '  | %s' "$(path_type "$path" "$capture")"
            first=0
        else
            printf '\n  | %s' "$(path_type "$path" "$capture")"
        fi
    done
    # `never` when a method has no routes: the call site then fails to compile
    # for every argument, which is the correct answer and not an empty union
    # that accepts anything.
    if test -z "$(printf '%s\n' "$rows" | awk -v m="$wanted" \
        '$1 == (m == "get" ? 1 : 2) { print }')"
    then
        printf '  | never'
    fi
    printf '\n'
}

cat <<'HEADER'
// Generated by scripts/client-ts.sh from the compiled route table.
//
// Do not edit. The table this was projected from is the table the dispatcher
// runs — `tests/boot/check.sh` regenerates this file and refuses a difference,
// so an edit here is reverted by the build rather than by a reviewer.
//
// A wrong path or a wrong method is a compile error at the call site:
//
//     await client.get("/sum");     // Error: "/sum" is not a GET route
//     await client.post("/hello");  // Error: "/hello" is not a POST route
//
// The status codes are the closed RouteResult the dispatcher returns, so a
// caller handling every member has handled every outcome the server has.

export type BootStatus = 200 | 404 | 405 | 413;

export interface BootResponse<T = unknown> {
  status: BootStatus;
  body: T;
  /** Present on 405 — the methods the dispatcher would have accepted. */
  allow?: readonly BootMethod[];
}

export type BootMethod = "get" | "post";

HEADER

printf 'export type GetPath =\n'
emit_route_union get
printf '\nexport type PostPath =\n'
emit_route_union post

cat <<'BODY'

export interface BootClientOptions {
  /** Base URL, e.g. "http://127.0.0.1:8080". No default: a client that
   *  silently picks a host is a client that talks to the wrong one. */
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
}

export function createClient(options: BootClientOptions) {
  const doFetch = options.fetch ?? globalThis.fetch;
  const base = options.baseUrl.replace(/\/+$/, "");

  async function send<T>(
    method: BootMethod,
    path: string,
    body?: unknown,
  ): Promise<BootResponse<T>> {
    const response = await doFetch(`${base}${path}`, {
      method: method.toUpperCase(),
      headers: body === undefined ? {} : { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const allow = response.headers.get("allow");
    return {
      status: response.status as BootStatus,
      body: (await response.json().catch(() => undefined)) as T,
      ...(allow
        ? { allow: allow.toLowerCase().split(/,\s*/) as BootMethod[] }
        : {}),
    };
  }

  return {
    get: <T = unknown>(path: GetPath) => send<T>("get", path),
    post: <T = unknown>(path: PostPath, body?: unknown) =>
      send<T>("post", path, body),
  };
}
BODY
