#!/bin/sh
set -eu

# Project the schema the seed printed into SQL.
#
#   scripts/ddl.sh schema [BUILT_SCHEMA]       the declared schema, as DDL
#   scripts/ddl.sh migrations [BUILT_SCHEMA]   the history, one statement per step
#
# The input is not a second declaration of the schema. It is the sections the
# schema binary itself prints — the declared schema, and the history it
# replayed — so SQL generated from those bytes cannot describe a column the
# core does not hold, or a step the core refused. The same rule the OpenAPI
# projection follows for the route table (ADR 4), for the same reason.
#
# Prisma commits the migration SQL it generates so a reviewer reads the SQL
# that will run; drizzle-kit does the same. That part is kept: both outputs are
# committed under contracts/ and tests/schema/check.sh regenerates them and
# fails on any difference. What is not kept is the SQL being the migration.
# Here the migration is a value, and the SQL is what the value looks like in
# one dialect.
#
# usage: scripts/ddl.sh schema|migrations [BUILT_SCHEMA]

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

fail() {
    printf 'ddl: %s\n' "$*" >&2
    exit 1
}

usage() {
    printf 'usage: scripts/ddl.sh schema|migrations [BUILT_SCHEMA]\n' >&2
    exit 2
}

mode=${1:-}
case $mode in
    schema|migrations) ;;
    *) usage ;;
esac

binary=${2:-}
if test -z "$binary"; then
    binary=$(SEED=schema sh "$ROOT/scripts/build-seed.sh" "$ROOT/build/schema")
fi
test -x "$binary" || fail "no built schema binary at $binary"

WORK=$(mktemp -d "${TMPDIR:-/tmp}/kofun-boot-ddl.XXXXXX")
trap 'rm -rf "$WORK"' 0 1 2 15

# An empty environment, so the projection cannot come to depend on one.
env -i "$binary" >"$WORK/out" || fail 'the schema binary exited non-zero'

test "$(sed -n 1p "$WORK/out")" = 'kofun-boot schema' ||
    fail 'the binary did not print a schema report'
contract=$(sed -n '/^contract$/{n;p;q;}' "$WORK/out")
test -n "$contract" || fail 'the schema report names no contract version'

# One named section, without its markers. A section that is absent or never
# closed is refused rather than read as empty.
section() {
    grep -qx "$1" "$WORK/out" || fail "the schema report has no '$1' section"
    grep -qx "end $1" "$WORK/out" || fail "the '$1' section is never closed"
    sed -n "/^$1\$/,/^end $1\$/p" "$WORK/out" | sed '1d;$d'
}

# The one seam the slice forces: the seed carries codes because a record
# cannot hold Text. Names live here, and every code must have one — a column
# added without a name fails rather than appearing in the SQL as a number.
table_name() {
    case $1 in
        1) printf 'users' ;;
        2) printf 'posts' ;;
        *) return 1 ;;
    esac
}

column_name() {
    case $1 in
        1) printf 'id' ;;
        2) printf 'email' ;;
        3) printf 'name' ;;
        4) printf 'display_name' ;;
        5) printf 'nickname' ;;
        6) printf 'author_id' ;;
        7) printf 'views' ;;
        *) return 1 ;;
    esac
}

kind_name() {
    case $1 in
        1) printf 'bigint' ;;
        2) printf 'text' ;;
        3) printf 'boolean' ;;
        4) printf 'integer' ;;
        *) return 1 ;;
    esac
}

# Resolution happens in this shell, never inside a command substitution: a
# `fail` inside `$( )` exits only the subshell, which is how the first version
# of the OpenAPI projection produced a document with a hole in it and a clean
# exit status.
need_table() {
    table_name "$1" >/dev/null || fail "table code $1 has no name; add it to scripts/ddl.sh"
}

need_column() {
    column_name "$1" >/dev/null || fail "column label $1 has no name; add it to scripts/ddl.sh"
}

need_kind() {
    kind_name "$1" >/dev/null || fail "column kind $1 has no SQL type; add it to scripts/ddl.sh"
}

null_clause() {
    if test "$1" = 0; then
        printf ' not null'
    fi
}

header() {
    printf -- '-- Generated by scripts/ddl.sh from the %s the schema binary printed.\n' "$1"
    printf -- '-- Do not edit: tests/schema/check.sh regenerates this file and fails on\n'
    printf -- '-- any difference.\n'
    printf -- '-- dialect: postgresql\n'
    printf -- '-- contract: %s\n' "$contract"
}

# Everything is written to a file first and printed only once the whole
# projection succeeded, so a refusal can never leave half a script on stdout.
OUT="$WORK/sql"

# ------------------------------------------------------------ the schema

project_schema() {
    section schema >"$WORK/schema"
    test "$(wc -l <"$WORK/schema" | tr -d ' ')" -eq 56 ||
        fail 'the schema section is not two tables of four header lines and four six-line keys'

    # Two tables of 28 lines each: four header lines, then four six-line keys.
    for offset in 0 28; do
        table=$(sed -n "$((offset + 1))p" "$WORK/schema")
        need_table "$table"
        sed -n "$((offset + 5)),$((offset + 28))p" "$WORK/schema" |
            paste - - - - - - >"$WORK/columns.$table"
    done

    # Resolve everything first. A reference names the other table's key; the
    # projection writes it with that key's current name, which is all SQL
    # can say, and orders tables so a referenced one is created first.
    for table in 1 2; do
        while IFS='	' read -r key label kind nullable state ref; do
            case $state in
                1)
                    need_column "$label"
                    need_kind "$kind"
                    if test "$ref" != 0; then
                        test "$table" = 2 ||
                            fail "table $table references a later table; the projection creates tables in code order"
                    fi
                    ;;
                0|2) ;;
                *) fail "table $table key $key has an unknown slot state $state" ;;
            esac
        done <"$WORK/columns.$table"
    done

    {
        header 'declared schema'
        for offset in 0 28; do
            table=$(sed -n "$((offset + 1))p" "$WORK/schema")
            primary=$(sed -n "$((offset + 2))p" "$WORK/schema")
            other=$((3 - table))
            primary_name=$(awk -F'\t' -v k="$primary" '$1 == k && $5 == 1 { print $2 }' "$WORK/columns.$table")
            test -n "$primary_name" || fail "table $table's primary key $primary is not a live column"
            printf '\n'
            printf 'create table %s (\n' "$(table_name "$table")"
            retired=''
            while IFS='	' read -r key label kind nullable state ref; do
                if test "$state" = 2; then
                    retired="$retired $key"
                fi
                test "$state" = 1 || continue
                references=''
                if test "$ref" != 0; then
                    target=$(awk -F'\t' -v k="$ref" '$1 == k && $5 == 1 { print $2 }' "$WORK/columns.$other")
                    test -n "$target" || fail "table $table key $key references key $ref, which is not live"
                    references=" references $(table_name "$other") ($(column_name "$target"))"
                fi
                printf '    %s %s%s%s, -- key %s\n' \
                    "$(column_name "$label")" "$(kind_name "$kind")" \
                    "$(null_clause "$nullable")" "$references" "$key"
            done <"$WORK/columns.$table"
            printf '    primary key (%s)\n' "$(column_name "$primary_name")"
            printf ');\n'
            if test -n "$retired"; then
                printf -- '-- %s: retired keys, never to be reissued:%s\n' "$(table_name "$table")" "$retired"
            fi
        done
    } >"$OUT"
}

# -------------------------------------------------------- the migrations

project_migrations() {
    section history >"$WORK/history"
    count=$(sed -n 1p "$WORK/history")
    case $count in
        ''|*[!0-9]*) fail 'the history section does not open with a step count' ;;
    esac
    test "$(sed -n '2,$p' "$WORK/history" | wc -l | tr -d ' ')" -eq $((count * 12)) ||
        fail "the history section does not hold $count twelve-line steps"
    sed -n '2,$p' "$WORK/history" | paste - - - - - - - - - - - - >"$WORK/steps"

    # Resolve every code first, and refuse a refused step: SQL for a step the
    # core declined would describe a database that never existed.
    while IFS='	' read -r step kind table key label column_kind nullable policy ref outcome payload live; do
        case $outcome in
            1|2|3|4|5|16) ;;
            *) fail "history step $step was refused by the core (outcome $outcome); there is no SQL for it" ;;
        esac
        need_table "$table"
        case $kind in
            1|2)
                need_column "$label"
                need_kind "$column_kind"
                ;;
            3) need_column "$label" ;;
            4|5) ;;
            6) need_kind "$column_kind" ;;
            *) fail "history step $step has an unknown migration kind $kind" ;;
        esac
    done <"$WORK/steps"

    # The name each (table, key) holds as the history advances. A rename or a
    # reference reads the current name from here; nothing reads it from the
    # step, because the step only knows the key.
    {
        header 'migration history'
        while IFS='	' read -r step kind table key label column_kind nullable policy ref outcome payload live; do
            tname=$(table_name "$table")
            other=$((3 - table))
            printf '\n'
            case $kind in
                1)
                    cname=$(column_name "$label")
                    eval "name_${table}_$key=\$cname"
                    printf -- '-- step %s: create table %s (primary key %s)\n' "$step" "$tname" "$key"
                    printf 'create table %s (\n' "$tname"
                    printf '    %s %s not null, -- key %s\n' "$cname" "$(kind_name "$column_kind")" "$key"
                    printf '    primary key (%s)\n' "$cname"
                    printf ');\n'
                    ;;
                2)
                    cname=$(column_name "$label")
                    eval "name_${table}_$key=\$cname"
                    references=''
                    if test "$ref" != 0; then
                        eval "target=\${name_${other}_$ref:-}"
                        test -n "$target" || fail "history step $step references key $ref of $(table_name "$other"), which no earlier step named"
                        references=" references $(table_name "$other") ($target)"
                    fi
                    printf -- '-- step %s: add column to %s (key %s)\n' "$step" "$tname" "$key"
                    if test "$nullable" = 0; then
                        printf -- '-- policy backfilled: the plan supplies the value for existing\n'
                        printf -- '-- rows; this projection does not invent one\n'
                    fi
                    printf 'alter table %s add column %s %s%s%s;\n' \
                        "$tname" "$cname" "$(kind_name "$column_kind")" "$(null_clause "$nullable")" "$references"
                    ;;
                3)
                    eval "old=\${name_${table}_$key:-}"
                    test -n "$old" || fail "history step $step renames key $key, which no earlier step named"
                    cname=$(column_name "$label")
                    eval "name_${table}_$key=\$cname"
                    printf -- '-- step %s: rename column of %s (key %s)\n' "$step" "$tname" "$key"
                    printf 'alter table %s rename column %s to %s;\n' "$tname" "$old" "$cname"
                    ;;
                4)
                    eval "old=\${name_${table}_$key:-}"
                    test -n "$old" || fail "history step $step drops key $key, which no earlier step named"
                    printf -- '-- step %s: drop column of %s (key %s), policy discard: its data is destroyed\n' \
                        "$step" "$tname" "$key"
                    printf 'alter table %s drop column %s;\n' "$tname" "$old"
                    ;;
                5)
                    eval "old=\${name_${table}_$key:-}"
                    test -n "$old" || fail "history step $step alters key $key, which no earlier step named"
                    if test "$nullable" = 0; then
                        printf -- '-- step %s: set not null on %s (key %s), policy backfilled\n' "$step" "$tname" "$key"
                        printf -- '-- precondition: every existing row already holds a value\n'
                        printf 'alter table %s alter column %s set not null;\n' "$tname" "$old"
                    else
                        printf -- '-- step %s: drop not null on %s (key %s)\n' "$step" "$tname" "$key"
                        printf 'alter table %s alter column %s drop not null;\n' "$tname" "$old"
                    fi
                    ;;
                6)
                    eval "old=\${name_${table}_$key:-}"
                    test -n "$old" || fail "history step $step changes the kind of key $key, which no earlier step named"
                    if test "$policy" = 1; then
                        # A narrowing under Discard: every value becomes null,
                        # which the core allowed only because the column is
                        # nullable.
                        printf -- '-- step %s: change kind on %s (key %s), policy discard: its values become null\n' \
                            "$step" "$tname" "$key"
                        printf 'alter table %s alter column %s type %s using null;\n' \
                            "$tname" "$old" "$(kind_name "$column_kind")"
                    else
                        printf -- '-- step %s: widen kind on %s (key %s); every value is kept\n' "$step" "$tname" "$key"
                        printf 'alter table %s alter column %s type %s;\n' \
                            "$tname" "$old" "$(kind_name "$column_kind")"
                    fi
                    ;;
            esac
        done <"$WORK/steps"
    } >"$OUT"
}

case $mode in
    schema) project_schema ;;
    migrations) project_migrations ;;
esac

cat "$OUT"
