#!/bin/sh
set -eu

# Project the loader's declared shapes, and its seed data, into SQL.
#
#   scripts/shape-sql.sh shapes [--dialect D] [BUILT_LOADER]
#   scripts/shape-sql.sh fixture N [BUILT_LOADER]
#
# The input is the `shapes` and `database` sections the loader binary printed.
# The core decides what each shape compiles to on each dialect, including
# refusing a join where the dialect has no LATERAL. This script only spells
# that decision in SQL. A shape it cannot name, or a dialect it has no
# spelling for, is refused before anything is printed.
#
# `shapes` writes contracts/shapes.sql for PostgreSQL. tests/loader/check.sh
# regenerates it and fails on any difference, and checks that the statements
# in each block are as many as the binary said the shape compiles to.
# `fixture N` writes the tables and N authors' rows that
# tests/loader/postgres.sh loads before measuring.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

fail() {
    printf 'shape-sql: %s\n' "$*" >&2
    exit 1
}

usage() {
    printf 'usage: scripts/shape-sql.sh shapes [--dialect postgresql|sqlite] [BUILT_LOADER]\n' >&2
    printf '       scripts/shape-sql.sh fixture N [BUILT_LOADER]\n' >&2
    exit 2
}

mode=${1:-}
test $# -gt 0 && shift
dialect=postgresql
authors=''
case $mode in
    shapes)
        if test "${1:-}" = --dialect; then
            dialect=${2:-}
            test $# -ge 2 || usage
            shift 2
        fi
        ;;
    fixture)
        authors=${1:-}
        test $# -gt 0 && shift
        case $authors in
            ''|*[!0-9]*) usage ;;
        esac
        ;;
    *) usage ;;
esac

binary=${1:-}
if test -z "$binary"; then
    binary=$(SEED=loader sh "$ROOT/scripts/build-seed.sh" "$ROOT/build/loader")
fi
test -x "$binary" || fail "no built loader binary at $binary"

WORK=$(mktemp -d "${TMPDIR:-/tmp}/kofun-boot-shape-sql.XXXXXX")
trap 'rm -rf "$WORK"' 0 1 2 15

env -i "$binary" >"$WORK/out" || fail 'the loader binary exited non-zero'
test "$(sed -n 1p "$WORK/out")" = 'kofun-boot loader' ||
    fail 'the binary did not print a loader report'
contract=$(sed -n '/^contract$/{n;p;q;}' "$WORK/out")

section() {
    grep -qx "$1" "$WORK/out" || fail "the loader report has no '$1' section"
    grep -qx "end $1" "$WORK/out" || fail "the '$1' section is never closed"
    sed -n "/^$1\$/,/^end $1\$/p" "$WORK/out" | sed '1d;$d'
}

# The seam the slice forces, as in the DDL and OpenAPI projections: codes in
# the binary, names here, and every code must have one.
dialect_code() {
    case $1 in
        postgresql) printf '1' ;;
        sqlite) printf '2' ;;
        *) return 1 ;;
    esac
}

relation_name() {
    case $1 in
        1) printf 'posts' ;;
        *) return 1 ;;
    esac
}

load_name() {
    case $1 in
        1) printf 'join' ;;
        2) printf 'split' ;;
        *) return 1 ;;
    esac
}

OUT="$WORK/sql"

project_shapes() {
    want=$(dialect_code "$dialect") || fail "unknown dialect '$dialect'"
    section shapes >"$WORK/shapes"
    count=$(sed -n 1p "$WORK/shapes")
    sed -n '2,$p' "$WORK/shapes" | paste - - - - - >"$WORK/rows"
    test "$(wc -l <"$WORK/rows" | tr -d ' ')" = "$count" ||
        fail "the shapes section does not hold $count five-line rows"

    # Refuse first, print later: the core's NeedsLateral is a build error, and
    # a refused shape must not leave the other shapes' SQL on stdout.
    while IFS='	' read -r load code outcome payload lateral; do
        test "$code" = "$want" || continue
        load_name "$load" >/dev/null || fail "load code $load has no name"
        if test "$outcome" = 2; then
            relation=$(relation_name "$payload") || fail "relation code $payload has no name"
            fail "a $(load_name "$load") of relation $relation cannot compile for $dialect: it has no LATERAL; declare $relation as split"
        fi
        test "$outcome" = 1 || fail "unknown shape outcome $outcome"
    done <"$WORK/rows"

    test "$dialect" = postgresql ||
        fail "no SQL spelling for dialect $dialect; only postgresql is projected"

    {
        printf -- '-- Generated by scripts/shape-sql.sh from the shapes the loader binary printed.\n'
        printf -- '-- Do not edit: tests/loader/check.sh regenerates this file and fails on\n'
        printf -- '-- any difference.\n'
        printf -- '-- dialect: postgresql\n'
        printf -- '-- contract: %s\n' "$contract"
        while IFS='	' read -r load code outcome payload lateral; do
            test "$code" = "$want" || continue
            printf '\n'
            case $(load_name "$load") in
                join)
                    printf -- '-- shape: authors with their post ids, load join: %s statement\n' "$payload"
                    printf 'select a.id, coalesce(children.post_ids, %s) as post_ids\n' "'[]'::json"
                    printf 'from authors a\n'
                    printf 'left join lateral (\n'
                    printf '    select json_agg(p.id order by p.id) as post_ids\n'
                    printf '    from posts p\n'
                    printf '    where p.author_id = a.id\n'
                    printf ') as children on true\n'
                    printf 'order by a.id;\n'
                    ;;
                split)
                    printf -- '-- shape: authors with their post ids, load split: %s statements\n' "$payload"
                    printf 'select a.id\n'
                    printf 'from authors a\n'
                    printf 'order by a.id;\n'
                    printf 'select p.author_id, json_agg(p.id order by p.id) as post_ids\n'
                    printf 'from posts p\n'
                    printf 'where p.author_id = any($1)\n'
                    printf 'group by p.author_id\n'
                    printf 'order by p.author_id;\n'
                    ;;
            esac
        done <"$WORK/rows"
    } >"$OUT"
}

project_fixture() {
    section database >"$WORK/database"
    capacity=$(sed -n 1p "$WORK/database")
    test "$authors" -le "$capacity" ||
        fail "the seed holds at most $capacity authors, asked for $authors"
    {
        printf -- '-- Seed data for %s authors, from the database the loader binary printed.\n' "$authors"
        printf 'create table authors (\n    id bigint primary key\n);\n'
        printf 'create table posts (\n'
        printf '    id bigint primary key,\n'
        printf '    author_id bigint not null references authors (id)\n'
        printf ');\n'
        author=1
        post=1
        while test "$author" -le "$authors"; do
            printf 'insert into authors (id) values (%s);\n' "$author"
            posts=$(sed -n "$((author + 1))p" "$WORK/database")
            n=1
            while test "$n" -le "$posts"; do
                printf 'insert into posts (id, author_id) values (%s, %s);\n' "$post" "$author"
                post=$((post + 1))
                n=$((n + 1))
            done
            author=$((author + 1))
        done
    } >"$OUT"
}

case $mode in
    shapes) project_shapes ;;
    fixture) project_fixture ;;
esac

cat "$OUT"
